format = """
$directory$git_branch$git_status$python$golang$java$cmd_duration
$character"""

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "* "

[git_status]
format = "([$all_status$ahead_behind]($style) )"

[python]
symbol = "py "
format = "[$symbol$version]($style) "
detect_files = ["requirements.txt", "pyproject.toml", "*.py"]

[golang]
symbol = "go "
format = "[$symbol$version]($style) "

[java]
symbol = "java "
format = "[$symbol$version]($style) "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[cmd_duration]
min_time = 2_000
format = "took [$duration]($style) "
